class AuthorityReportGenerator
  CATEGORIES = {
    "csam" => "Child Sexual Abuse Material (CSAM)",
    "threats" => "Credible Threats of Violence",
    "terrorism" => "Terrorism",
    "other_illegal" => "Other Illegal Activity"
  }.freeze

  def initialize(message, category:, reporter:)
    @message = message
    @category = category
    @reporter = reporter
  end

  def generate
    lines = []
    lines << "=" * 60
    lines << "INFERNO — REPORT FOR LAW ENFORCEMENT"
    lines << "=" * 60
    lines << ""
    lines << "Generated: #{Time.current.utc.strftime('%Y-%m-%d %H:%M:%S UTC')}"
    lines << "Report Category: #{CATEGORIES[@category] || @category}"
    lines << ""
    lines << "-" * 60
    lines << "MESSAGE DETAILS"
    lines << "-" * 60
    lines << ""
    lines << "Message ID: #{@message.public_id}"
    lines << "Nostr Event ID: #{@message.nostr_event_id || 'N/A (local message)'}"
    lines << "Timestamp: #{@message.created_at&.utc&.strftime('%Y-%m-%d %H:%M:%S UTC') || 'Unknown'}"
    lines << ""

    lines << "Sender Nostr Public Key: #{@message.nostr_author_pubkey || 'N/A (local user)'}"
    if @message.user.present?
      lines << "Sender Username: #{@message.user.username}"
      lines << "Sender Display Name: #{@message.user.display_name}" if @message.user.display_name.present?
    end
    lines << ""

    if @message.channel.present?
      lines << "Server: #{@message.channel.server&.name || 'Unknown'}"
      lines << "Channel: ##{@message.channel.name}"
      if @message.channel.server&.nostr_group_id.present?
        lines << "Server Nostr Group ID: #{@message.channel.server.nostr_group_id}"
      end
    elsif @message.conversation.present?
      lines << "Context: Direct Message"
      lines << "Conversation ID: #{@message.conversation.public_id}"
    end
    lines << ""

    lines << "-" * 60
    lines << "MESSAGE CONTENT"
    lines << "-" * 60
    lines << ""
    if @message.hidden_reason == "csam_match"
      lines << "[Content blocked by automated safety systems — not displayed]"
    elsif @message.content.present?
      lines << @message.content
    else
      lines << "[No text content]"
    end
    lines << ""

    if @message.hidden_attachment_records.any?
      lines << "-" * 60
      lines << "ATTACHMENT METADATA"
      lines << "-" * 60
      lines << ""
      lines << "Note: Attachments were purged on hide. Only metadata is included."
      lines << "Law enforcement can retrieve original content from Nostr relays"
      lines << "using the Event ID above with proper legal authority."
      lines << ""
      @message.hidden_attachment_records.each_with_index do |rec, i|
        lines << "  Attachment #{i + 1}:"
        lines << "    Filename: #{rec.original_filename}"
        lines << "    Content Type: #{rec.content_type}"
        lines << "    Size: #{rec.byte_size} bytes"
        lines << "    Checksum: #{rec.checksum}"
        lines << "    Purged At: #{rec.purged_at&.utc&.strftime('%Y-%m-%d %H:%M:%S UTC')}"
        lines << ""
      end
    end

    relays = RelayConnection.active.pluck(:url)
    if relays.any?
      lines << "-" * 60
      lines << "RELAY INFORMATION"
      lines << "-" * 60
      lines << ""
      lines << "The message was seen on these Nostr relays:"
      relays.each { |url| lines << "  - #{url}" }
      lines << ""
      lines << "Law enforcement can request the original event (including any"
      lines << "attachments) from these relays using the Nostr Event ID above."
      lines << ""
    end

    lines << "-" * 60
    lines << "REPORTER INFORMATION"
    lines << "-" * 60
    lines << ""
    lines << "Reporter Username: #{@reporter.username}"
    lines << "Reporter Nostr Public Key: #{@reporter.nostr_public_key || 'N/A'}"
    lines << ""

    lines << "-" * 60
    lines << "MODERATION HISTORY"
    lines << "-" * 60
    lines << ""
    lines << "Hidden At: #{@message.hidden_at&.utc&.strftime('%Y-%m-%d %H:%M:%S UTC')}"
    lines << "Hidden Reason: #{@message.hidden_reason}"
    lines << ""

    lines << "=" * 60
    lines << "HOW TO USE THIS REPORT"
    lines << "=" * 60
    lines << ""
    lines << "This report was generated by the Inferno messaging application."
    lines << "It contains metadata and identifiers that law enforcement can use"
    lines << "to investigate the reported content."
    lines << ""
    lines << "To retrieve the original content (including images/videos),"
    lines << "law enforcement should request the Nostr event with the Event ID"
    lines << "listed above from the relays listed in this report."
    lines << ""
    lines << "REPORTING RESOURCES:"
    lines << "  CSAM: NCMEC CyberTipline — https://report.cybertip.org"
    lines << "  Terrorism/Threats: FBI IC3 — https://ic3.gov"
    lines << "  UK: Internet Watch Foundation — https://iwf.org.uk"
    lines << "  EU: Europol — https://europol.europa.eu/report-a-crime"
    lines << ""
    lines << "=" * 60

    lines.join("\n")
  end
end
