module EmojiHelper
  EMOJIS = {
    "Smileys" => %w[😀 😃 😄 😁 😆 😅 🤣 😂 🙂 🙃 😉 😊 😇 🥰 😍 🤩 😘 😗 😚 😙 🥲 😋 😛 😜 🤪 😝 🤑 🤗 🤭 🤫 🤔 🫡 🤐 🤨 😐 😑 😶 🫥 😏 😒 🙄 😬 🤥 😌 😔 😪 🤤 😴 😷 🤒 🤕 🤢 🤮 🥵 🥶 🥴 😵 🤯 🤠 🥳 🥸 😎 🤓 🧐 😡 😠 🤬 😈 👿 💀 💩 🤡 👻 👽 🤖],
    "Gestures" => %w[👍 👎 👊 ✊ 🤛 🤜 👏 🙌 👐 🤲 🤝 🙏 ✌️ 🤞 🤟 🤘 👌 🤌 🤏 👈 👉 👆 👇 ☝️ ✋ 🤚 🖐️ 🖖 👋 🤙 💪 🦾 🖕],
    "Hearts" => %w[❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 ❤️‍🔥 ❤️‍🩹 💕 💞 💓 💗 💖 💘 💝 💟],
    "Objects" => %w[🔥 ⭐ 🌟 ✨ 💫 🎉 🎊 🎈 🎁 🏆 🥇 🎮 🎯 🎲 🔮 💎 💰 💡 📌 📎 ✏️ 📝 💻 ⌨️ 🖥️ 📱 ☎️ 📷 🎵 🎶 🎸 🎹 🍕 🍔 🍺 🍷 ☕]
  }

  EMOJI_NAMES = {
    "😀" => "grinning", "😃" => "smiley", "😄" => "smile", "😁" => "grin", "😆" => "laughing",
    "😅" => "sweat smile", "🤣" => "rofl", "😂" => "joy", "🙂" => "slightly smiling",
    "🙃" => "upside down", "😉" => "wink", "😊" => "blush", "😇" => "innocent angel",
    "🥰" => "smiling hearts love", "😍" => "heart eyes", "🤩" => "star struck", "😘" => "kissing heart",
    "😗" => "kissing", "😚" => "kissing closed eyes", "😙" => "kissing smiling eyes",
    "🥲" => "smiling tear", "😋" => "yum delicious", "😛" => "tongue out", "😜" => "winking tongue",
    "🤪" => "zany crazy", "😝" => "squinting tongue", "🤑" => "money face rich",
    "🤗" => "hugging hug", "🤭" => "hand over mouth giggle", "🤫" => "shushing quiet",
    "🤔" => "thinking hmm", "🫡" => "saluting salute", "🤐" => "zipper mouth shut",
    "🤨" => "raised eyebrow suspicious", "😐" => "neutral", "😑" => "expressionless",
    "😶" => "no mouth silent", "🫥" => "dotted line invisible", "😏" => "smirk smug",
    "😒" => "unamused annoyed", "🙄" => "eye roll", "😬" => "grimace awkward",
    "🤥" => "lying pinocchio", "😌" => "relieved calm", "😔" => "pensive sad",
    "😪" => "sleepy tired", "🤤" => "drooling", "😴" => "sleeping zzz",
    "😷" => "mask sick", "🤒" => "thermometer fever", "🤕" => "head bandage hurt",
    "🤢" => "nauseated sick", "🤮" => "vomiting throw up", "🥵" => "hot sweating",
    "🥶" => "cold freezing", "🥴" => "woozy drunk dizzy", "😵" => "knocked out dizzy",
    "🤯" => "mind blown exploding head", "🤠" => "cowboy hat", "🥳" => "partying celebration",
    "🥸" => "disguised", "😎" => "cool sunglasses", "🤓" => "nerd glasses",
    "🧐" => "monocle curious", "😡" => "angry pouting", "😠" => "angry mad",
    "🤬" => "cursing swearing", "😈" => "devil smiling imp", "👿" => "angry devil imp",
    "💀" => "skull dead", "💩" => "poop poo", "🤡" => "clown", "👻" => "ghost boo",
    "👽" => "alien", "🤖" => "robot",
    "👍" => "thumbs up yes like", "👎" => "thumbs down no dislike", "👊" => "fist bump punch",
    "✊" => "raised fist", "🤛" => "left fist", "🤜" => "right fist",
    "👏" => "clap applause", "🙌" => "raising hands celebrate", "👐" => "open hands",
    "🤲" => "palms up", "🤝" => "handshake deal", "🙏" => "pray please thanks folded hands",
    "✌️" => "peace victory", "🤞" => "crossed fingers luck", "🤟" => "love you rock",
    "🤘" => "rock on horns metal", "👌" => "ok okay perfect", "🤌" => "pinched italian",
    "🤏" => "pinching small tiny", "👈" => "pointing left", "👉" => "pointing right",
    "👆" => "pointing up", "👇" => "pointing down", "☝️" => "index up one",
    "✋" => "raised hand stop high five", "🤚" => "raised back of hand",
    "🖐️" => "hand splayed fingers", "🖖" => "vulcan spock", "👋" => "wave hello bye",
    "🤙" => "call me hang loose shaka", "💪" => "flexed bicep strong muscle",
    "🦾" => "mechanical arm prosthetic", "🖕" => "middle finger",
    "❤️" => "red heart love", "🧡" => "orange heart", "💛" => "yellow heart",
    "💚" => "green heart", "💙" => "blue heart", "💜" => "purple heart",
    "🖤" => "black heart", "🤍" => "white heart", "🤎" => "brown heart",
    "💔" => "broken heart", "❤️‍🔥" => "heart on fire passion", "❤️‍🩹" => "mending heart healing",
    "💕" => "two hearts", "💞" => "revolving hearts", "💓" => "heartbeat beating",
    "💗" => "growing heart", "💖" => "sparkling heart", "💘" => "heart arrow cupid",
    "💝" => "heart ribbon gift", "💟" => "heart decoration",
    "🔥" => "fire hot lit flame", "⭐" => "star", "🌟" => "glowing star shining",
    "✨" => "sparkles magic", "💫" => "dizzy star", "🎉" => "party popper tada",
    "🎊" => "confetti ball", "🎈" => "balloon party", "🎁" => "gift present wrapped",
    "🏆" => "trophy winner cup", "🥇" => "gold medal first", "🎮" => "game controller joystick",
    "🎯" => "bullseye target dart", "🎲" => "dice game", "🔮" => "crystal ball fortune",
    "💎" => "gem diamond jewel", "💰" => "money bag cash", "💡" => "light bulb idea",
    "📌" => "pushpin pin", "📎" => "paperclip", "✏️" => "pencil write",
    "📝" => "memo note write", "💻" => "laptop computer", "⌨️" => "keyboard type",
    "🖥️" => "desktop computer monitor", "📱" => "phone mobile", "☎️" => "telephone phone call",
    "📷" => "camera photo", "🎵" => "music note", "🎶" => "music notes",
    "🎸" => "guitar", "🎹" => "piano keyboard music", "🍕" => "pizza food",
    "🍔" => "burger hamburger food", "🍺" => "beer mug drink", "🍷" => "wine glass drink",
    "☕" => "coffee hot beverage tea"
  }.freeze
end
